---

name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] <Scope> - "
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you want.
      options:
        - label: I have searched the existing issues
          required: true
    validations:
      required: true
  - type: textarea
    id: why-feature
    attributes:
      label: Why?
      description: Is your feature request related to a problem? Please describe
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: what-feature
    attributes:
      label: What?
      description: Describe the solution you would like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you have considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Additional context
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: Please note that I won't just add features simply because you request them, my time is limited so if you would like to see a feature you should consider if and how you can contribute it yourself.

...
