return {
    {
        "                _  _                ",
        "               ( \\/ )               ",
        "        .---.   \\  /   .-\"-.        ",
        "       /   6_6   \\/   / 4 4 \\       ",
        "       \\_  (__\\       \\_ v _/       ",
        "       //   \\\\        //   \\\\       ",
        "      ((     ))      ((     ))      ",
        "=======\"\"===\"\"========\"\"===\"\"=======",
        "         |||            |||         ",
        "          |              |          ",
    },
    {
        "                        OOOOO          OOOOO                        ",
        "                       OO   OOO      OOO   OO                       ",
        "                       OO     OOO  OOO     OO                       ",
        "                        OOO     OOOO     OOO                        ",
        "      OOOOOO          OO  OOOOOO    OOOOOO  OO          OOOOOO      ",
        "   OOOO    OOOOO   OOOO                      OOOO   OOOOO    OOOO   ",
        "               OOOOO     VVVVVV      VVVVVV     OOOOO               ",
        "                       VVVVVVVVVV  VVVVVVVVVV                       ",
        "                     VVVVVVVVVVVVVVVVVVVVVVVVVV                     ",
        "                     VVVVVVVVVVVVVVVVVVVVVVVVVV                     ",
        "        XXXXXX       VVVVVVVVVVVVVVVVVVVVVVVVVV      XXXXXXX        ",
        "     XXXXXXXXXXX      VVVVVVVVVVVVVVVVVVVVVVVV      XXXXXXXXXXX     ",
        "    XXXXXXXXXXXXX      VVVVVVVVVVVVVVVVVVVVVV      XXXXXXXXXXXXX    ",
        "   XXXXXXXXXXXXXXXX     VVVVVVVVVVVVVVVVVVVV     XXXXXXXXXXXXXXXX   ",
        "   XXXXXXXXXXXXXXXX      VVVVVVVVVVVVVVVVVV      XXXXXXXXXXXXXXXX   ",
        "   XXXXXXXXXXXXXXXX     XXVVVVVVVVVVVVVVVVXX     XXXXXXXXXXXXXXXX   ",
        "    XXXXXXXXXXXXXXXX    XXXVVVVVVVVVVVVVVXXX    XXXXXXXXXXXXXXXX    ",
        "       XXXXXXXXXXX     XXXX VVVVVVVVVVVV XXXX     XXXXXXXXXXX       ",
        "           XXXXXXX    XXXX   VVVVVVVVVV   XXXX    XXXXXXX           ",
        "    XXXXXX  XXXXXXXXXXXXXX    VVVVVVVV    XXXXXXXXXXXXXX  XXXXXX    ",
        "  XXXXXXXXXXXXXXXXXXXXXX       VVVVVV       XXXXXXXXXXXXXXXXXXXXXX  ",
        " XXXXXXXXXXXXXXXXXXXX           VVVV           XXXXXXXXXXXXXXXXXXXX ",
        "XX XXXXX XXXXXXXXXXXX            VV            XXXXXXXXXXXX XXXXX XX",
        "X  X XX  XXXXXXXXXXXX                          XXXXXXXXXXXX  XX X  X",
        "     X  XXXXXXXXXXXX                            XXXXXXXXXXXX  X     ",
        "       XXXXXXXXXXXXX                            XXXXXXXXXXXXX       ",
        "       XXXXXXXXXXXXXX                          XXXXXXXXXXXXXX       ",
        "       XXXXXXXXXXXXXXX                        XXXXXXXXXXXXXXX       ",
        "        XXXXXXXXXXXXXXX                      XXXXXXXXXXXXXXX        ",
        "       XXXXXXX  XXXXXXXX                    XXXXXXXX  XXXXXXX       ",
        "      XXXXXXX     XXXXXXX                  XXXXXXX     XXXXXXX      ",
        " XXXXXXXXXXX        XXXXXX                XXXXXX        XXXXXXXXXXX ",
        " XXXXXXXXX           XXXXX                XXXXX           XXXXXXXXX ",
        " XXXX                 XXXXX              XXXXX                 XXXX ",
        "  XXX                  XXXXX            XXXXX                  XXX  ",
        "                        XXXX            XXXX                        ",
    },
    {
        "                               (                                      ",
        "                      .-'''-..' \\                         Who the...??",
        "            _______ .'       -   \\                           yikes!   ",
        "          <<<<<<<< );__   ,,,_)   \\                      __ /         ",
        "             <<<<<<<<< ) ;C  /     \\                /ZZZ'  )          ",
        "               <<<<<< (.-'-.  )====_)_=======>      .-'``'>>>>>>>>>>  ",
        "                 <<<<< \\    '''''''   )           .'    >>>>>>>>>     ",
        "                 ;  <<<     .......__/       __\\_;    ,>>>>>>>        ",
        "            .-'''         (         )          / / ('\"\\__             ",
        "         .-'              ;.       /            (;/;) /\\              ",
        "        /  .-'     .     =  .     /                                   ",
        "    _-''\\_/         '. .'    .   /                                    ",
        " .-'  )  ;\\          '''.     . /                                     ",
        ";   .''''  `.       '    ;     (                                      ",
        "O -'        .'''       .'                                             ",
        "          .'   .-'''''`                                               ",
        "          'o-'                                                        ",
    },
    {
        "      _____           _____      ",
        "  ,ad8PPPP88b,     ,d88PPPP8ba,  ",
        " d8P\"      \"Y8b, ,d8P\"      \"Y8b ",
        "dP'           \"8a8\"           `Yd",
        "8(              \"              )8",
        "I8                             8I",
        " Yb,                         ,dP ",
        "  \"8a,                     ,a8\"  ",
        "    \"8a,                 ,a8\"    ",
        "      \"Yba             adP\"      ",
        "        `Y8a         a8P'        ",
        "          `88,     ,88'          ",
        "            \"8b   d8\"            ",
        "             \"8b d8\"             ",
        "              `888'              ",
        "                \"                ",
    },
    {
        "         (\\/)             ",
        "          \\/              ",
        "  (\\/)   .-.  .-.         ",
        "   \\/   ((`-)(-`))        ",
        "         \\\\    //   (\\/)  ",
        "          \\\\  //     \\/   ",
        "   .=\"\"\"=._))((_.=\"\"\"=.   ",
        "  /  .,   .'  '.   ,.  \\  ",
        " /__(,_.-'      '-._,)__\\ ",
        "`    /|             |\\   `",
        "    /_|__         __|_\\   ",
        "      | `))     ((` |     ",
        "      |             |     ",
        "     -\"==         ==\"-    ",
    },
    {
        "oo                                             ",
        "   oo     @@@@@@@@:       @@@@@@@@!            ",
        "      o@@@@!!!!;;;;@    @@.......:;!@          ",
        "     'O@@!!!;;;;;;;;@  @.......:   ;!@         ",
        "     @@@!!!!;;::::::.@@........:    ;!@        ",
        "     @@!!!!;;:::::..............:   ;!@        ",
        "     @@@!!!;::::::..............:   ;!@        ",
        "      @@!!;;::::::.............:   ;!@         ",
        "       @@!;;::::::......oo.....::::!@          ",
        "         @!!;::::::........oo..:::@            ",
        "           !!!;:::::..........oo@              ",
        "              !!;:::::.......@   oo      *     ",
        "                ;;::::.....@        oo   ***   ",
        "                   :::..@              ooo*##  ",
        "                     ::.             _##ooo### ",
        "                      :            **##########",
    },
    {
        " .,,. .,,.                                                         ",
        ":XXXX,XXXX:                   .SSSSSSS'                            ",
        "'XXXXXXXXX'                 .SSSSSSSS,WW:,  .''':,.                ",
        " ':XXXXX:'                .SSSSSSSSSS:WWW:,       '::,             ",
        "   'XXX'                 .SSSSSSSSS,WWW( )WW        '::,  '////    ",
        "    ':'                  SSSSSSSSSSSS'WWWWWWD         '::,////     ",
        "                   ,.    SSSSSSS(((SSSWWWWW          ,WW//:.'.W.   ",
        "                 ,((()   'SSSSSS(((WWWWWWWWWW)        //'W,:WWWW'  ",
        "               ,(((((()   'SSSSSS((WWWWWWWWWW)      //   'WWW,WWW  ",
        "            .,(((((((())    'SSSSWWWWWWWWWWW'     //     .WWWWW:,  ",
        "         .,((((((((((())),     SSWWWWWWWWWW'    //      ,WWWW' ':, ",
        "     .,((((((((((((((())))),.,,,,WWWWWWWWWW:, //       ,WWWWW'  ': ",
        "'((((((((((((((((((((()))))WWWWWWWWWWWWWVVVV//WWWWW:,.,WWWWW'    : ",
        "   ((((((((((((((((((()))(WWWWWWWWWWWWWWVVVVVVWWWWWWWWWWWWW'    '  ",
        "     ((((((((((((((((()))(WWWWWWWWWWWWWVVVVVVVWWWWWWWWWWWW'        ",
        "       (((((((((((((())(()(WWWWWWWWW.VVVVVVVWWWWWWWWWWW:'          ",
        "           ((((((((())) ()(WWWWWW.VVVVVVV'WWWWWWW''      .,,. .,,. ",
        "              ((((()))   ((WW,VVVVVVVVV'WWWWWWWWW       :XXXX,XXXX:",
        "                           WVVVVVVVVVV'WWWWWWWW:'       'XXXXXXXXX'",
        "     .,,. .,,.             VVVVVVVVV'WWWWWWWWWW          ':XXXXX:' ",
        "    :XXXX,XXXX:          .WVVVVVVV'WWWWWWWWWWWW            'XXX'   ",
        "    'XXXXXXXXX'         .WWW''''',WWWWWWWWWWWW:             ':'    ",
        "     ':XXXXX:'        (())))WWWWWWWWWWWWWWWWW'                     ",
        "       'XXX'         ((())))))WWWWWWWWWWWWWW'                      ",
        "        ':'         ((()))))))))WWWWWWWWWWW'                       ",
        "                    ()WWWWWW))))))))))))))))                       ",
        "                    :WWWWWWWWW))))))))))))))     .,,. .,,.         ",
        "                    WWWWWWWWWWW)))))))WWWWW.    :XXXX,XXXX:        ",
        "                   :WWWWWWWWWW')))))WWWWWWWW.   'XXXXXXXXX'        ",
        "                   WWWWWWWWWW'  'WWWWWWWWWWWW    ':XXXXX:'         ",
        "         .,,:WWWW:,WWWWWWWWW'    'WWWWWWWWWWW      'XXX'           ",
        "        ,WWWWWWWWWWWWWWWWWW'       'WWWWWWWWW       ':'            ",
        "       ,WWWWWWWWWWWWWWWWWW'         'WWWWWWWW,                     ",
        "       WWWWWWW'   '':WWW:'           'WWWWWWWW                     ",
        "     .WWWWWWW'                      .WWWWWWWWW                     ",
        "     ''W'W'WW                      ,WWWWWWWWW'          .,,. .,,.  ",
        "           ''                     ,WWWWWWWW'           :XXXX,XXXX: ",
        "           .,,. .,,.             .WWWWWW:'             'XXXXXXXXX' ",
        "          :XXXX,XXXX:         .WWWWWWW'                 ':XXXXX:'  ",
        "          'XXXXXXXXX'         WWWWWW'                     'XXX'    ",
        "           ':XXXXX:'           WWWWW'                      ':'     ",
        "             'XXX'              WWWW.                              ",
        "              ':'               'WWWWW,                            ",
        "                                 '' ''                             ",
    },
}
